### ISSUE TITLE
"An error occurred while saving the article" on shared hosting installation

### ISSUE THREAD

**Issue by minosimo** [wallabag/wallabagger#373]
Similar to #264, I get this error when saving any article, but I am using the shared host package. I have attached a log. The relevant line appears to be:
`[2023-11-05T13:23:22.765535+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getAttributes" of class "ReflectionClass"." at /home/user/web/wallabag.myhost.com/public_html/vendor/jms/serializer/src/Metadata/Driver/AttributeDriver/AttributeReader.php line 29 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\Unde
[Uploading prod.log…]()
finedMethodError(code: 0): Attempted to call an undefined method named \"getAttributes\" of class \"ReflectionClass\". at /home/user/web/wallabag.myhost.com/public_html/vendor/jms/serializer/src/Metadata/Driver/AttributeDriver/AttributeReader.php:29)"} []`

The article does actually get saved, but the "Indicate if page already saved" does not work, nor can tags be added from the extension.

I double checked that the required modules from [here](https://doc.wallabag.org/en/admin/installation/requirements) are installed and enabled, and ran a `composer install` just in case, but that doesn't seem to have changed the behavior.

Maybe this belongs in a separate issue, but the Android app also cannot fetch articles from wallabag, though authentication and connection works. The log for that is:
```
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
	at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
	at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
	at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
	at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Now

```

**Comment by Simounet** [comment]
Does seems to be a wallabagger issue but a wallabag one. You should check/open an issue on [the main repository](https://github.com/wallabag/wallabag).
