### ISSUE TITLE
Can get API Token

### ISSUE THREAD

**Issue by FredK27** [wallabag/wallabagger#413]
![Wallabager](https://github.com/user-attachments/assets/05b61d27-02d6-4066-99f3-56484015e18f)

I am running Wallabag in a docker container. I've gotten the Wallabag iPhone app to use my Client ID, Client Secret, Login and Password to access my saved pages successfully.

I cannot get the Wallbagger Chrome extension to generate an API token. I've tried disabling all of the other extensions that I am running in Chrome and I still can't get an API token.

I am running Wallabag in a docker container and I am using it with traefik. Access to wallabag via https works fine to view my saved pages and to generate the Client ID and Client secret.

I really like this app would would appreciate some help to get the Chrome extension to work. I am running Chrome on the latest version of macOS.

**Comment by Simounet** [comment]
Hi there,
Could you open the console (press F12) before clicking on the "Get token" button and let me know if any request from the `Network` tab returns a code other than 200.
Do you have any error in the `Console` tab?

**Comment by curtosis** [comment]
Maybe helpful in troubleshooting; I'm getting an `invalid grant` error on v2.5.4 behind Yunohost -- wallabag is returning HTTP 400.

**Comment by newillusions** [comment]
I'm seeing the same here, too.

**Comment by jnobbe** [comment]
+1

I'm getting, `Uncaught Error: Attempting to use a disconnected port object
    at OptionsController.getAppTokenClick (options.js:255:23)` and `options.js:160 Uncaught Error: Attempting to use a disconnected port object
    at OptionsController.allowExistCheckClick (options.js:160:23)`.

I'm trying it on Vivaldi 7.0.3495.26 (Stable channel) stable (64-bit)

**Comment by daviddelven** [comment]
Same here (Firefox and also Arc Browser (chromium based)).

**Comment by Daviddj13** [comment]
Same here, I´m trying with Edge Navigator.

**Comment by Daviddj13** [comment]
Here the message
![Issue](https://github.com/user-attachments/assets/33601ec4-053c-49ff-8ee5-e19110d23ed2)

**Comment by mrpeverill** [comment]
I'm getting the same 'uncaught error: attempting to use a disconnected port object. I've tried Chrome and Vivaldi.

**Comment by Daviddj13** [comment]
I finally get it. Try today.

**Comment by gregeeh** [comment]
I'm getting the same 'uncaught error: attempting to use a disconnected port object. I've tried Chrome and Brave.  Any ideas on how to solve would be appreciated.

**Comment by Simounet** [comment]
Hi there, was it a fresh install for all of you?

**Comment by gregeeh** [comment]
> Hi there, was it a fresh install for all of you?

Fresh install of what?  Docker install was untouched.  Installed the Chrome Extension on different PC's and getting the same error.  Continues to work on PC's that had the Extension previously installed.

Hope that answers your question.

**Comment by Simounet** [comment]
Fresh install of the wallabagger addon.

**Comment by gregeeh** [comment]
> Fresh install of the wallabagger addon.

Yes, fresh install of Wallabagger Extension.

**Comment by Simounet** [comment]
For everyone on this topic, could you give me:
- the OS you're using
- browser name
- browser version
- wallabag API version

**Comment by gregeeh** [comment]
> For everyone on this topic, could you give me:
> 
> * the OS you're using
> * browser name
> * browser version
> * wallabag API version

Windows 11 and Linux Mint
Brave Release Notes v1.73.104 (Dec 19, 2024) and Chrome Version 131.0.6778.205 (Official Build) (64-bit)
API 2.6.10

**Comment by jnobbe** [comment]
@Simounet , I just tried and got:
```
Uncaught Error: Attempting to use a disconnected port object
    at OptionsController.getAppTokenClick (options.js:255:23)
```

Operating System: EndeavourOS 
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.8-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Vivaldi 7.0.3495.27 (Stable channel) stable (64-bit), revision f9c950389d095d05cf6a3b76e495eb65dfb0cf85
Wallabag: 2.6.10

**Comment by Rurik19** [comment]
temporary solution = save setup to file, refresh setup page, load from file, this time error doesn't appear. (don't forget press "checkUrl" again to accept permission request). Checked on Chromium, Vivaldi on Windows 11, (on FF cannot get this error)

**Comment by jnobbe** [comment]
@Simounet , this may be a minor detail but I want to add that even when I create a new client and just after I release the mouse button from clicking "Get token", the "wallabag API token" message will say "Expired" briefly before changing to "Not granted".

**Comment by gregeeh** [comment]
> temporary solution = save setup to file, refresh setup page, load from file, this time error doesn't appear. (don't forget press "checkUrl" again to accept permission request). Checked on Chromium, Vivaldi on Windows 11, (on FF cannot get this error)

This worked for me.  Thanks.

**Comment by HolgerAusB** [comment]
60 minutes is standard and wallabagger should renew it automaticallly

**Comment by jnobbe** [comment]
Adding this screenshot to the conversation.

I've tried on Windows 11 now as well with the same result. I tried the workaround method as well, still no dice on my end.

This is after opening Options and clicking "Get token", and also "Check URL/Get token". The fields are validating but the token is showing as expired.

![Image](https://github.com/user-attachments/assets/c3f0d060-8604-4528-9729-f8900eb5c864)

**Comment by mobilestack** [comment]
still have the same problem for chrome

**Comment by mobilestack** [comment]
> temporary solution = save setup to file, refresh setup page, load from file, this time error doesn't appear. (don't forget press "checkUrl" again to accept permission request). Checked on Chromium, Vivaldi on Windows 11, (on FF cannot get this error)

after trying this more times, it works now

**Comment by ihcbbs** [comment]
经过测试，需要在扩展管理中授权“允许访问文件 URL”
After testing, it is necessary to authorize “Allow access to file URLs” in Extension Manager.

**Comment by agluck91** [comment]
@Simounet I am getting 
```
options.js:255 Uncaught Error: Attempting to use a disconnected port object
    at OptionsController.getAppTokenClick (options.js:255:23)
```
Chrome Version: Version 133.0.6943.141 (Official Build) 
OS: NixOS 24.11
WM: Hyprland Latest Stable.
Compositor: Wayland 
Wallabag Docker image: latest
Chrome Extention version: 1.18.0


I am able to connect all of my other devices with no trouble using the same client information, so I know the tokens and credentials are all in working order. Under the networking tab there is no traffic at all it never gets to the point that it tries to send the token request. 

I have done as ihcbbs has recommended as well and "Allow Access to File URLs". It did not resolve the issue. 

I am happy to collect logs.

I have also rebooted and reinstalled the app.

**Comment by Simounet** [comment]
Hi there, I've got a workaround but I need you to try it.

@FredK27 @curtosis @newillusions @jnobbe @daviddelven @Daviddj13 @gregeeh @mobilestack @agluck91 @Xenu-Ams 

1. download [this packaged extension](https://github.com/user-attachments/files/20638028/wallabagger.crx.zip) file
2. remove the `.zip`extension from the filename, you should have a file named `wallabagger.crx` instead of `wallabagger.crx.zip`
3. go to this URL (it's your browser extension page)
    - Chrome: `chrome://extensions/`
    - Vivaldi: `vivaldi:extensions`
    - Brave: `brave://extensions/`
4. enable the developer mode (toggle on the top right corner)
5. get the extension file from your file browser and drag 'n drop it to this page
6. accept to install it

**Comment by banterCZ** [comment]
> temporary solution = save setup to file, refresh setup page, load from file, this time error doesn't appear. (don't forget press "checkUrl" again to accept permission request). Checked on Chromium, Vivaldi on Windows 11, (on FF cannot get this error)

This workaround works for me. Mac OS 15.5 M1, Brave 1.79.119 (arm64)

**Comment by jnobbe** [comment]
@Simounet , sorry I'm late to the party on this. I had removed Wallabag but was encouraged to try again. I've just tested the extension and it is working in Vivaldi on EndeavourOS (Arch Linux.) Thank you!

**Comment by Simounet** [comment]
@jnobbe Good to know. Thank you for your patience and I hope that you are a new wallabag happy user. 😄

**Comment by Xenu-Ams** [comment]
Yes, works with newest plugin on Brave. Thanks!!
